apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert -f K8s/docker-compose.yml -o K8s/base
    kompose.image-pull-secret: regcred
    kompose.service.expose: 3.91.63.14.nip.io
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: customers-service
  name: customers-service
spec:
  rules:
    - host: 3.91.63.14.nip.io
      http:
        paths:
          - backend:
              serviceName: customers-service
              servicePort: 8081
status:
  loadBalancer: {}
